-- Database Schema for Laboratory Sample Management System
CREATE DATABASE IF NOT EXISTS lab_management;
USE lab_management;

-- Roles Table
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Insert Default Roles
INSERT IGNORE INTO roles (name) VALUES 
('Administrator'), 
('Reception Secretary'), 
('Assignment Secretary'), 
('Resident / Doctor'), 
('Laboratory Manager');

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_id INT NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Insert an initial admin user (password will be 'admin123', assuming bcrypt hash will be generated by backend, but for SQL initialization we might just create it via API later. I am inserting a sample hash for 'admin123' generated with bcrypt)
-- Using a standard bcrypt hash for 'admin123': $2b$10$AAx/PZmI/bQHmnh21n3aZOcQxqFNPPVdNbufyeJpOXBTLpPd.7UZW
INSERT IGNORE INTO users (role_id, username, password, first_name, last_name) 
VALUES (1, 'admin', '$2b$10$AAx/PZmI/bQHmnh21n3aZOcQxqFNPPVdNbufyeJpOXBTLpPd.7UZW', 'System', 'Admin');

-- Patients Table
CREATE TABLE IF NOT EXISTS patients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Samples Table
CREATE TABLE IF NOT EXISTS samples (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    date_received DATE NOT NULL,
    status ENUM('Received', 'Assigned', 'In Analysis', 'Completed', 'Archived') DEFAULT 'Received',
    patient_id INT NOT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Assignments Table
CREATE TABLE IF NOT EXISTS assignments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sample_id INT NOT NULL,
    user_id INT NOT NULL,  -- The Resident/Doctor assigned to the sample
    assigned_by INT NOT NULL, -- The Secretary who assigned it
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sample_id) REFERENCES samples(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE CASCADE
);

-- History Table
CREATE TABLE IF NOT EXISTS history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sample_id INT NOT NULL,
    user_id INT NOT NULL,
    action VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sample_id) REFERENCES samples(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
